### ISSUE TITLE
proposal: code environment templates

### ISSUE THREAD

**Issue by lus** [ranna-go/ranna#22]
Hey ^^.

I recently got the idea to implement so-called code environment templates into ranna to allow code execution without having to provide the whole boilerplate (package, imports, main function) that surrounds the expression to evaluate.
I also made up my mind on how this could possibly be implemented in the current solution to create as little friction as possible.

## Specification implementation

First of all, `spec.yml` entries receive an additional field called `template`:

```yml
golang:
  image: 'golang:alpine'
  entrypoint: 'go run'
  filename: 'main.go'
  example: |-
    package main
    import "fmt"
    func main() {
    	fmt.Println("Hello world!")
    }
  template: |-
    package main
    import "fmt"
    func main() {
    	$${CODE}
    }
```

`$${CODE}` gets replaced with the user-provided expression before passing the whole construct down to the execution runtime.

## API implementation

The `POST /v1/exec` request body receives an additional field called `inline_expression` (boolean).
If this field is set to `true`, the contents of the `code` field get inserted in the desired template.
If the specification of the targetted language does not support inline templating (the `template` field is omitted), an error is returned.
The `inline_expression` field is set to `false` by default to not break existing API clients.

```json
{
  "language": "go",
  "code": "fmt.Println(\"Cool! Inline expressions!\")",
  "inline_expression": true,
  "arguments": [],
  "environment": {}
}
```

Please let me know what you think of this idea and my suggested example on how to implement it!
If you would like to implement this into ranna, I'd love to help with a PR.

**Comment by zekroTJA** [comment]
Yeah, I actually think this is a really good idea. Especially when thinking of the usage in applications like shinpuru, this would massively simplify the process of running code, especially in languages like go or java. 

Would be also cool if you could auto-detect if it is an inline expression or not. I am thinking of code execution with shinpuru, for example, so that you can pass code in the inline format or as a whole without the need to provide the "mode" beforehand. This could be accomplished by using different modes for `inline_expression` like `0 → off`, `1 → on`, `2 → autodetect`.

**Comment by lus** [comment]
Yes, auto-detection was also an idea that came to my mind, but I'm not really sure how to concretely implement this.
One could use spec-specific rules (for Go an expression is inline if it does not start with `package` for example) which provide a nice and extensible way of making sure that the detection is as accurate as possible for every language.

**Comment by zekroTJA** [comment]
Well, your right, auto-detection might become very inaccurate depending on the language. And also, I never wanted to have something like code analysis stuff directly in ranna, because it is just not the purpose of this particular service.

So I would prefer going the way with the `inline_expression` flag and providing it explicitly each time.

**Comment by lus** [comment]
Yup. Ranna is the code execution engine in the first place; auto-detection of these things can be implemented by shinpuru directly if it's a wanted feature in my opinion.
